version: "3.8"

services:
  d-code:
    image: d-code:latest
    build: .
    container_name: "DockerVScode"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    tty: true

    restart: on-failure
